---
title: "SubtypeME"
output: html_document
---

**GBM**   
For the GBM subtype classification we use 4 expression subtypes (Classical, Mesenchymal, Neural, Proneural) as defined in [Verhaak RG. et al. 2010](http://www.ncbi.nlm.nih.gov/pubmed/20129251).   
   
**LGG**  
For the LGG subtype classification we use 3 molecular subtypes (IDH mutant with 1p/19q codeletion, IDH mutant without 1p/19q codeletion, IDH wild-type) as defined in [NEJM, 2015](http://www.ncbi.nlm.nih.gov/pubmed/26061751).            
   
Classification algorithms:       
* The Subtype call generated by **Support Vector Machine (SVM)**, is done performing a linear Kernel with 10-fold cross validation, using the `ksvm` function of the [‘kernlab’](http://cran.r-project.org/web/packages/kernlab/kernlab.pdf) package. As training dataset for the GBM we use the TCGA GBM samples described in [Brennan C. et al. 2013](http://www.ncbi.nlm.nih.gov/pubmed/24120142). As training dataset for the LGG we use the TCGA LGG samples described in [NEJM, 2015](http://www.ncbi.nlm.nih.gov/pubmed/26061751).             
* The **K-nearest neighbor (K-NN)** Subtype calls, are obtained using the `knn3Train` function of the [‘caret’](http://cran.r-project.org/web/packages/caret/caret.pdf) package, using the subtypes as in the SVM calls.  
* The Subtype call generated  by single sample **Gene Set Enrichment Analysis (ssGSEA)**, is done using the `gsva` function of the [‘gsva’](http://www.bioconductor.org/packages/2.12/bioc/html/GSVA.html) package (method = "ssgsea"). For GBM samples classification we uses the 840 gene classifier as defined in [Verhaak RG. et al. 2010](http://www.ncbi.nlm.nih.gov/pubmed/20129251). Not available yet for LGG samples.   

The "3-Way" tab (GBM samples only) generates Subtype calls with the tree methods (SVM, K-NN and ssGSEA) and compare them, giving a "majority vote". In case the three methods give three different outputs for a specific sample, the vote will be assigned arbitrary (by alphabetical order).  
