---
title: "Single sample Gene Set Enrichment Analysis (ssGSEA)"
output: html_document
---

Single-sample GSEA (ssGSEA), an extension of Gene Set Enrichment Analysis
(GSEA), calculates separate enrichment scores for each pairing of a sample and gene
set. Each ssGSEA enrichment score represents the degree to which the genes in a
particular gene set are coordinately up- or down-regulated within a sample. In this
manner ssGSEA projects a single sample’s gene expression profile from the space of
single genes onto the space of gene sets. Any supervised or unsupervised machine
learning technique can then be applied to the resulting projected dataset. The benefit
here is that the ssGSEA projection transforms the data to a higher-level (pathways
instead of genes) space representing a more biologically interpretable set of features on
which analytic methods can be applied. (Ref:[*GenePattern*](http://www.broadinstitute.org/cancer/software/genepattern/modules/docs/ssGSEAProjection/4)).      

* The Subtype call generated by  **ssGSEA**, is done using the `gsva` function of the [‘gsva’](http://www.bioconductor.org/packages/2.12/bioc/html/GSVA.html) package (method = "ssgsea"). For GBM samples classification we uses the 840 gene classifier as defined in [Verhaak RG. et al. 2010](http://www.ncbi.nlm.nih.gov/pubmed/20129251). Not available yet for LGG samples.   


